name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3

      - name: Auto Dependabot
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            jamesmoreton/generate@master
            jamesmoreton/jamesmoreton@main
          FILES: |
            sync/workflows/auto-dependabot.yml=.github/workflows/auto-dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
          GIT_USERNAME: jamesmoreton

      - name: Dependabot (Actions)
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            jamesmoreton/jamesmoreton@main
          FILES: |
            sync/dependabot/dependabot-actions.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
          GIT_USERNAME: jamesmoreton
          GIT_EMAIL: james_moreton@hotmail.co.uk
