name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3

      - name: Auto Dependabot
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            jamesmoreton/generate@master
          FILES: |
            sync/workflows/auto-dependabot.yml=.github/workflows/auto-dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
          GIT_USERNAME: jamesmoreton
