name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v3

      - name: Auto Dependabot
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            jamesmoreton/algorithms@master
            jamesmoreton/appointment-finder@main
            jamesmoreton/generate@master
            jamesmoreton/grepr@main
            jamesmoreton/jamesmoreton@main
            jamesmoreton/remindee@main
            jamesmoreton/tweet-gen@master
            jamesmoreton/sandbox@master
          FILES: |
            sync/workflows/auto-dependabot.yml=.github/workflows/auto-dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}

      - name: Dependabot (Actions)
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            jamesmoreton/jamesmoreton@main
            jamesmoreton/tweet-gen@master
          FILES: |
            sync/dependabot/dependabot-actions.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}

      - name: Dependabot (Actions & Maven)
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            jamesmoreton/algorithms@master
            jamesmoreton/appointment-finder@main
            jamesmoreton/jax-rs-server@master
            jamesmoreton/persistence@master
            jamesmoreton/sandbox@master
            jamesmoreton/spring-server@master
          FILES: |
            sync/dependabot/dependabot-actions-maven.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
