name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v4

      - name: Auto Dependabot
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
          FILES: |
            sync/workflows/auto-dependabot.yml=.github/workflows/auto-dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}

      - name: Dependabot (Actions)
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
          FILES: |
            sync/dependabot/dependabot-actions.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}

      - name: Dependabot (Actions & Maven)
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
          FILES: |
            sync/dependabot/dependabot-actions-maven.yml=.github/dependabot.yml
          TOKEN: ${{ secrets.ACTIONS }}
